info:
  component: Gateway Server

spring:
  #main:
  # web-application-type: REACTIVE
  jmx:
    enabled: false
  cloud:
    bootstrap.enabled: false
    gateway:
      default-filters:
      - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      routes:
      - id: wiremock-server
        uri: http://localhost:7006
        predicates:
        - Path=/v1/reward-memberships/abc
        filters:
        - SampleWriteResponse
        - SampleResponseDecorator
        #- SampleResponseDecoratorV2

server:
  port: 7007
  ssl:
    enabled: false

logging:
  level:
    org.sample: ERROR
    org.springframework.cloud.gateway: ERROR
    org.springframework.http.server.reactive: ERROR
    org.springframework.web.reactive: ERROR
    reactor.ipc.netty: ERROR
    io.netty.channel: ERROR
